### ISSUE TITLE
Missing requirements

### ISSUE THREAD

**Issue by ilyasst** [arpcorrea/curly-octo-couscous#1]
Hello,

I have tried running the code, I followed these steps:
`python3 -m venv .env`
`pip install -r requirements.txt`
`python main.py`

I get an error about missing matplotlib. I believe that other packages are missing, could you please add them to requirements.txt ?

Cheers,
Ilyass

**Comment by arpcorrea** [comment]
requirements.txt has been updated. Thank you!
